//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Resume.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Db_ResumeEntities : DbContext
    {
        public Db_ResumeEntities()
            : base("name=Db_ResumeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_About> Tbl_About { get; set; }
        public virtual DbSet<Tbl_Admin> Tbl_Admin { get; set; }
        public virtual DbSet<Tbl_Certificates> Tbl_Certificates { get; set; }
        public virtual DbSet<Tbl_Educations> Tbl_Educations { get; set; }
        public virtual DbSet<Tbl_Experiences> Tbl_Experiences { get; set; }
        public virtual DbSet<Tbl_Interests> Tbl_Interests { get; set; }
        public virtual DbSet<Tbl_Languages> Tbl_Languages { get; set; }
        public virtual DbSet<Tbl_Skills> Tbl_Skills { get; set; }
        public virtual DbSet<Tbl_Contact> Tbl_Contact { get; set; }
    }
}
