//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Resume.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Certificates
    {
        public int CertificateId { get; set; }
        public string CertificateTitle { get; set; }
        public string CertificateOrganization { get; set; }
        public string CertificateTime { get; set; }
        public string CertificateDate { get; set; }
        public string CertificateUrl { get; set; }
    }
}
