//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Resume.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Educations
    {
        public int EducationId { get; set; }
        public string EducationTitle { get; set; }
        public string EducationSubtitle { get; set; }
        public string EducationDescription { get; set; }
        public string EducationAvg { get; set; }
        public string EducationDate { get; set; }
    }
}
