//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Resume.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Experiences
    {
        public int ExperienceId { get; set; }
        public string ExperienceTitle { get; set; }
        public string ExperienceSubtitle { get; set; }
        public string ExperienceDescription { get; set; }
        public string ExperienceDate { get; set; }
    }
}
