//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Resume.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_About
    {
        public int AboutId { get; set; }
        public string AboutName { get; set; }
        public string AboutSurname { get; set; }
        public string AboutAddress { get; set; }
        public string AboutMail { get; set; }
        public string AboutPhone { get; set; }
        public string AboutContext { get; set; }
        public string AboutGitHub { get; set; }
        public string AboutLinkedin { get; set; }
        public string AboutImage { get; set; }
    }
}
